 INSERT INTO estados (estado, id_pais) VALUES ('Dolj', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Guangdong', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Trabzon', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Cochabamba', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('Huanuco', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Zachodnio-Pomorskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Antananarivo', 98);
 INSERT INTO estados (estado, id_pais) VALUES ('Galicia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Scotland', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('Basel-Stadt', 161);
 INSERT INTO estados (estado, id_pais) VALUES ('Bahia', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Home Island', 211);
 INSERT INTO estados (estado, id_pais) VALUES ('East Kasai', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Namibe', 6);
 INSERT INTO estados (estado, id_pais) VALUES ('Shan', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Toskent Shahri', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Ha Darom', 60);
 INSERT INTO estados (estado, id_pais) VALUES ('Amur', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Bacau', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Shiga', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Nizni Novgorod', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Norte de Santander', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Bayamón', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Manisa', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Mwanza', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Huambo', 6);
 INSERT INTO estados (estado, id_pais) VALUES ('Rio Grande do Norte', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Banaadir', 155);
 INSERT INTO estados (estado, id_pais) VALUES ('Managua', 119);
 INSERT INTO estados (estado, id_pais) VALUES ('Fukui', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Kalimantan Timur', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Kosovo and Metohija', 67);
 INSERT INTO estados (estado, id_pais) VALUES ('East Java', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Qadarif', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Burjatia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Västmanlands län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Arequipa', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Murcia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Miaoli', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Podlaskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Rhode Island', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Namangan', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Thimphu', 20);
 INSERT INTO estados (estado, id_pais) VALUES ('Kwara & Kogi', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('North Ireland', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('Ha Merkaz', 60);
 INSERT INTO estados (estado, id_pais) VALUES ('Eastern Cape', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Harare', 191);
 INSERT INTO estados (estado, id_pais) VALUES ('Zapadní Cechy', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Csongrád', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Dac Lac', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Herat', 1);
 INSERT INTO estados (estado, id_pais) VALUES ('Perm', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Adygea', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Aceh', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Khan Yunis', 232);
 INSERT INTO estados (estado, id_pais) VALUES ('St. Catherine', 63);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Minufiya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Languedoc-Roussillon', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Nicosia', 88);
 INSERT INTO estados (estado, id_pais) VALUES ('Apulia', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Kerala', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Haryana', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Mandalay', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Ceará', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Bushehr', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Rajshahi', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Tjumen', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Copperbelt', 144);
 INSERT INTO estados (estado, id_pais) VALUES ('Buzau', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Manitoba', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Borno & Yobe', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Hwanghae N', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Saint-Pierre', 226);
 INSERT INTO estados (estado, id_pais) VALUES ('Western Visayas', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Kirov', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Wakayama', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Noord-Brabant', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Umbria', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Groningen', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Tarapacá', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Kerman', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Abruzzit', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Maputo', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaliningrad', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Potosí', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('La Libertad', 36);
 INSERT INTO estados (estado, id_pais) VALUES ('Pohjois-Pohjanmaa', 158);
 INSERT INTO estados (estado, id_pais) VALUES ('Zonguldak', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Rakhine', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('La Paz', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('Perak', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Liguria', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Siem Reap', 68);
 INSERT INTO estados (estado, id_pais) VALUES ('Jerusalem', 60);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Manama', 14);
 INSERT INTO estados (estado, id_pais) VALUES ('Tibet', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Baluchistan', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('Quang Nam-Da Nang', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Maysan', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Yunnan', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Navarra', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Karabük', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Opolskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Conakry', 49);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 152);
 INSERT INTO estados (estado, id_pais) VALUES ('North Austria', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('Catamarca', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Santa Fé', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Saipan', 220);
 INSERT INTO estados (estado, id_pais) VALUES ('Lambayeque', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Moskova', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Aomori', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Western Mindanao', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Borsod-Abaúj-Zemplén', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Nord', 52);
 INSERT INTO estados (estado, id_pais) VALUES ('Greater Accra', 46);
 INSERT INTO estados (estado, id_pais) VALUES ('Hanti-Mansia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Khartum', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('San Luis Potosí', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Kadiogo', 27);
 INSERT INTO estados (estado, id_pais) VALUES ('Dayr al-Zawr', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Mehedinti', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Gifu', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Asunción', 129);
 INSERT INTO estados (estado, id_pais) VALUES ('Osh', 76);
 INSERT INTO estados (estado, id_pais) VALUES ('Sakarya', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Sardinia', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Východné Slovensko', 153);
 INSERT INTO estados (estado, id_pais) VALUES ('Yamanashi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Taoyuan', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Tyva', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Najran', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Anhui', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Luxembourg', 97);
 INSERT INTO estados (estado, id_pais) VALUES ('KwaZulu-Natal', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Canary Islands', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Krasnodar', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Maranhão', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('DhiQar', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Houet', 27);
 INSERT INTO estados (estado, id_pais) VALUES ('Campania', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Limassol', 88);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Visayas', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Táchira', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Podkarpackie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Nakhon Ratchasima', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Sokoto & Kebbi & Zam', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Xinxiang', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Andorra la Vella', 5);
 INSERT INTO estados (estado, id_pais) VALUES ('Örebros län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Adana', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Najaf', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Bicol', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Suez', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Samarkand', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Vaduz', 95);
 INSERT INTO estados (estado, id_pais) VALUES ('Asyut', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Isparta', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Massachusetts', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Quindío', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Salzburg', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('Atlántida', 53);
 INSERT INTO estados (estado, id_pais) VALUES ('Nghe An', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Coahuila de Zaragoza', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Yazd', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Canterbury', 181);
 INSERT INTO estados (estado, id_pais) VALUES ('Trentino-Alto Adige', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Rio Grande do Sul', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Nakhon Sawan', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Riyadh', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Lara', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Bahr al-Ahmar', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Overijssel', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Puerto Plata', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Sistan va Baluchesta', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Mazandaran', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Attika', 84);
 INSERT INTO estados (estado, id_pais) VALUES ('Riad', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Zambézia', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Tomsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Iowa', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Chaouia-Ouardigha', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Macau', 213);
 INSERT INTO estados (estado, id_pais) VALUES ('Hanoi', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Uttar Pradesh', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Tortola', 198);
 INSERT INTO estados (estado, id_pais) VALUES ('Ayacucho', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Tianjin', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 129);
 INSERT INTO estados (estado, id_pais) VALUES ('Kyonggi', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Brunei and Muara', 25);
 INSERT INTO estados (estado, id_pais) VALUES ('Grande-Terre', 205);
 INSERT INTO estados (estado, id_pais) VALUES ('Usak', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Córdoba', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Samara', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Minnesota', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Abhasia [Aphazeti]', 45);
 INSERT INTO estados (estado, id_pais) VALUES ('Berliini', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Gäncä', 12);
 INSERT INTO estados (estado, id_pais) VALUES ('Extrême-Nord', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Tasmania', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Nova Scotia', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Fort-de-France', 214);
 INSERT INTO estados (estado, id_pais) VALUES ('Karbala', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Lima', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Kansas', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Nord', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Mayagüez', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Saarland', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaolack', 149);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Luzon', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Guárico', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Braila', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Magwe [Magway]', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Hajdú-Bihar', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Lovec', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Lubelskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Bretagne', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Rivers & Bayelsa', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Wellington', 181);
 INSERT INTO estados (estado, id_pais) VALUES ('Jaroslavl', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Bács-Kiskun', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Zürich', 161);
 INSERT INTO estados (estado, id_pais) VALUES ('Kalimantan Barat', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Ismailia', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Rio de Janeiro', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Bac Thai', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamburg', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Puebla', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Kirovograd', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Camagüey', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Marinmaa', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('South Kazakstan', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Rhône-Alpes', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Yerevan', 10);
 INSERT INTO estados (estado, id_pais) VALUES ('Haifa', 60);
 INSERT INTO estados (estado, id_pais) VALUES ('Van', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Mpumalanga', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Honiara', 143);
 INSERT INTO estados (estado, id_pais) VALUES ('Cusco', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Shandong', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Andalusia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Ba kortostan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Panevezys', 96);
 INSERT INTO estados (estado, id_pais) VALUES ('Sulawesi Selatan', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Sarawak', 102);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 185);
 INSERT INTO estados (estado, id_pais) VALUES ('Pahang', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Hatay', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Limousin', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Balti', 111);
 INSERT INTO estados (estado, id_pais) VALUES ('Jalisco', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Grad Zagreb', 85);
 INSERT INTO estados (estado, id_pais) VALUES ('Cluj', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Primorje', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Mogiljov', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Mendoza', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Tien Giang', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Ariana', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Qalyubiya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Ruse', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Nariño', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Stavropol', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Thiès', 149);
 INSERT INTO estados (estado, id_pais) VALUES ('Western Cape', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Pultava', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Free State', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Chubut', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Volynia', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Erzurum', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Konya', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Braga', 131);
 INSERT INTO estados (estado, id_pais) VALUES ('Saint-Louis', 149);
 INSERT INTO estados (estado, id_pais) VALUES ('Neamt', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Cheju', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Vitebsk', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Taitung', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Nagasaki', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Nothwest Border Prov', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('Marrakech-Tensift-Al', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Qom', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Fujian', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Misiones', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Medina', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Nuevo León', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Osaka', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Hsinchu', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('New Providence', 13);
 INSERT INTO estados (estado, id_pais) VALUES ('Anhalt Sachsen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Nara', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Cortés', 53);
 INSERT INTO estados (estado, id_pais) VALUES ('Veracruz', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Giza', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Molukit', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Zarqa', 66);
 INSERT INTO estados (estado, id_pais) VALUES ('Harkova', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Taipei', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Dhaka', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Fargona', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Elâzig', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Saksi', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Penza', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Rajasthan', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Omsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('St George Basseterre', 139);
 INSERT INTO estados (estado, id_pais) VALUES ('Junín', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('North Ossetia-Alania', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Franche-Comté', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Ibb', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('Ontario', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Esmeraldas', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Fyn', 166);
 INSERT INTO estados (estado, id_pais) VALUES ('Nantou', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Uppsala län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Bangui', 74);
 INSERT INTO estados (estado, id_pais) VALUES ('Maritime', 168);
 INSERT INTO estados (estado, id_pais) VALUES ('Markazi', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Miyagi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Iasi', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Can Tho', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Saratov', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Arad', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Adiyaman', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Keelung', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Sonora', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Hawaii', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Jammu and Kashmir', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Taichung', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Hebron', 232);
 INSERT INTO estados (estado, id_pais) VALUES ('Ouest', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Colorado', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Komi', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Gansu', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Babil', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Kocaeli', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Navoi', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Habarovsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Funafuti', 176);
 INSERT INTO estados (estado, id_pais) VALUES ('Eskisehir', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Mato Grosso do Sul', 192);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 229);
 INSERT INTO estados (estado, id_pais) VALUES ('Hhohho', 160);
 INSERT INTO estados (estado, id_pais) VALUES ('Uttaranchal', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Campeche', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Jujuy', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Bremen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Ibaragi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Kermanshah', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Vologda', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Bali', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Gabès', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('Qandahar', 1);
 INSERT INTO estados (estado, id_pais) VALUES ('Pirkanmaa', 158);
 INSERT INTO estados (estado, id_pais) VALUES ('Northern', 46);
 INSERT INTO estados (estado, id_pais) VALUES ('South Dakota', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Amhara', 40);
 INSERT INTO estados (estado, id_pais) VALUES ('Chandigarh', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Ahal', 175);
 INSERT INTO estados (estado, id_pais) VALUES ('Saint GeorgeŽs', 197);
 INSERT INTO estados (estado, id_pais) VALUES ('Yünlin', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('La Habana', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Sumy', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Central', 53);
 INSERT INTO estados (estado, id_pais) VALUES ('Magallanes', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('La Rioja', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Goiás', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Daugavpils', 90);
 INSERT INTO estados (estado, id_pais) VALUES ('Binh Dinh', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('South Kivu', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Jiangsu', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Vilna', 96);
 INSERT INTO estados (estado, id_pais) VALUES ('Ashanti', 46);
 INSERT INTO estados (estado, id_pais) VALUES ('Zuid-Holland', 2);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 206);
 INSERT INTO estados (estado, id_pais) VALUES ('Qasim', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Hubei', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Montana', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Addis Abeba', 40);
 INSERT INTO estados (estado, id_pais) VALUES ('Western', 118);
 INSERT INTO estados (estado, id_pais) VALUES ('Gujarat', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Tongatapu', 169);
 INSERT INTO estados (estado, id_pais) VALUES ('', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('T et enia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Shefa', 184);
 INSERT INTO estados (estado, id_pais) VALUES ('St George', 32);
 INSERT INTO estados (estado, id_pais) VALUES ('Frederiksberg', 166);
 INSERT INTO estados (estado, id_pais) VALUES ('Tainan', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Sulawesi Tenggara', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Maule', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('West Irian', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Federal Capital Dist', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Terengganu', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Paraíba', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Skåne län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Republika Srpska', 22);
 INSERT INTO estados (estado, id_pais) VALUES ('Atlántico', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Nablus', 232);
 INSERT INTO estados (estado, id_pais) VALUES ('East Götanmaan län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Sumatera Utara', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Ouémé', 19);
 INSERT INTO estados (estado, id_pais) VALUES ('Guerrero', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Sharja', 8);
 INSERT INTO estados (estado, id_pais) VALUES ('Khuzestan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Minas Gerais', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Mahajanga', 98);
 INSERT INTO estados (estado, id_pais) VALUES ('Pennsylvania', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Astrahan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Guanajuato', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('La Libertad', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Meta', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Centre', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Atlantique', 19);
 INSERT INTO estados (estado, id_pais) VALUES ('West Island', 211);
 INSERT INTO estados (estado, id_pais) VALUES ('Gaziantep', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('T ernivtsi', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Port-of-Spain', 170);
 INSERT INTO estados (estado, id_pais) VALUES ('Tlemcen', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Formosa', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Kumamoto', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Hawalli', 87);
 INSERT INTO estados (estado, id_pais) VALUES ('Brazzaville', 80);
 INSERT INTO estados (estado, id_pais) VALUES ('Gilan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Baki', 12);
 INSERT INTO estados (estado, id_pais) VALUES ('Bolívar', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Logone Occidental', 171);
 INSERT INTO estados (estado, id_pais) VALUES ('Almaty Qalasy', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Thüringen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Antalya', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Qazvin', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Federaatio', 22);
 INSERT INTO estados (estado, id_pais) VALUES ('Gaza', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Toyama', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Taejon', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('New York', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Daqahliya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Federal', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 41);
 INSERT INTO estados (estado, id_pais) VALUES ('Kurgan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Rogaland', 122);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Sulaymaniya', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Shamal', 92);
 INSERT INTO estados (estado, id_pais) VALUES ('Tiroli', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('Niigata', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Western', 156);
 INSERT INTO estados (estado, id_pais) VALUES ('León', 119);
 INSERT INTO estados (estado, id_pais) VALUES ('Lisboa', 131);
 INSERT INTO estados (estado, id_pais) VALUES ('Emilia-Romagna', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Aleksandria', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Luxor', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Qasim', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Sibiu', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Auckland', 181);
 INSERT INTO estados (estado, id_pais) VALUES ('Idaho', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Dong Nai', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Kvemo Kartli', 45);
 INSERT INTO estados (estado, id_pais) VALUES ('Mangghystau', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Raqqa', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Béchar', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Yogyakarta', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Southern Mindanao', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Gorj', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Kagoshima', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Calabria', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Asir', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Caldas', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Taza-Al Hoceima-Taou', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Dubai', 8);
 INSERT INTO estados (estado, id_pais) VALUES ('Damascus', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Plaines Wilhelms', 108);
 INSERT INTO estados (estado, id_pais) VALUES ('Thua Thien-Hue', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Duarte', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Nacional', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Samsun', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Pyongan P', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Belgorod', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Nairobi', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Okinawa', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Khon Kaen', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Mecklenburg-Vorpomme', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Tenasserim [Tanintha', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Caroni', 170);
 INSERT INTO estados (estado, id_pais) VALUES ('São Tiago', 71);
 INSERT INTO estados (estado, id_pais) VALUES ('Southern Tagalog', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Karjala', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Gumma', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Port-Louis', 108);
 INSERT INTO estados (estado, id_pais) VALUES ('Wien', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('Lombardia', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Outer Harbour', 104);
 INSERT INTO estados (estado, id_pais) VALUES ('Ouest', 52);
 INSERT INTO estados (estado, id_pais) VALUES ('San José', 30);
 INSERT INTO estados (estado, id_pais) VALUES ('Kitaa', 204);
 INSERT INTO estados (estado, id_pais) VALUES ('Provence-Alpes-Côte', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Cayo', 18);
 INSERT INTO estados (estado, id_pais) VALUES ('Aksaray', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Wallis', 230);
 INSERT INTO estados (estado, id_pais) VALUES ('Brest', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Idlib', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Texas', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Negeri Sembilan', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Tabora', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Rheinland-Pfalz', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Balikesir', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Crete', 84);
 INSERT INTO estados (estado, id_pais) VALUES ('Chuuk', 110);
 INSERT INTO estados (estado, id_pais) VALUES ('Burgas', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Vinnytsja', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Doukkala-Abda', 105);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 195);
 INSERT INTO estados (estado, id_pais) VALUES ('New Jersey', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Rivne', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Rondônia', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Queensland', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Diourbel', 149);
 INSERT INTO estados (estado, id_pais) VALUES ('Kiova', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Nakhon Pathom', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Maradi', 120);
 INSERT INTO estados (estado, id_pais) VALUES ('British Colombia', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Darfur al-Janubiya', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Arges', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Cayenne', 222);
 INSERT INTO estados (estado, id_pais) VALUES ('Tekirdag', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Pomorskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Hadramawt', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('Irrawaddy [Ayeyarwad', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('West Azerbaidzan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('West Java', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Almaty', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Misrata', 94);
 INSERT INTO estados (estado, id_pais) VALUES ('Aqtöbe', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Tocantins', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Mingäçevir', 12);
 INSERT INTO estados (estado, id_pais) VALUES ('Hail', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('San Marino', 146);
 INSERT INTO estados (estado, id_pais) VALUES ('Sumqayit', 12);
 INSERT INTO estados (estado, id_pais) VALUES ('Kirikkale', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Tottori', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Tirana', 3);
 INSERT INTO estados (estado, id_pais) VALUES ('Sanaa', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('Limburg', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Valparaíso', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Quetzaltenango', 48);
 INSERT INTO estados (estado, id_pais) VALUES ('Cajamarca', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Udon Thani', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Gaza', 232);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 217);
 INSERT INTO estados (estado, id_pais) VALUES ('Blantyre', 100);
 INSERT INTO estados (estado, id_pais) VALUES ('Zacatecas', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Toa Baja', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Niamey', 120);
 INSERT INTO estados (estado, id_pais) VALUES ('La Araucanía', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Zanzibar West', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Východní Cechy', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Kursk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Anzoátegui', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Tamil Nadu', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Java', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Portuguesa', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Kurdufan al-Shamaliy', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Tabasco', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Zytomyr', 178);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 210);
 INSERT INTO estados (estado, id_pais) VALUES ('Banjul', 44);
 INSERT INTO estados (estado, id_pais) VALUES ('Cantabria', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Connecticut', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Sverdlovsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Neuquén', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Gaborone', 23);
 INSERT INTO estados (estado, id_pais) VALUES ('Denizli', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Chollabuk', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Fukuoka', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Prahova', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Djibouti', 31);
 INSERT INTO estados (estado, id_pais) VALUES ('Alabama', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Western', 46);
 INSERT INTO estados (estado, id_pais) VALUES ('Antwerpen', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Coast', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Montevideo', 180);
 INSERT INTO estados (estado, id_pais) VALUES ('Nord-Ouest', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Botosani', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Toskent', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Hasaka', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Asima', 87);
 INSERT INTO estados (estado, id_pais) VALUES ('Kyongsangnam', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Podravska', 154);
 INSERT INTO estados (estado, id_pais) VALUES ('Serravalle/Dogano', 146);
 INSERT INTO estados (estado, id_pais) VALUES ('Biserta', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('Saskatchewan', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Novosibirsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Picardie', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Kwangju', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Anbar', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Bahr al-Abyad', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Benguela', 6);
 INSERT INTO estados (estado, id_pais) VALUES ('Los Ríos', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Chongqing', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Leinster', 58);
 INSERT INTO estados (estado, id_pais) VALUES ('Hualien', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Batman', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Sumatera Selatan', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Tadla-Azilal', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Riau', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Chiayi', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Haiphong', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Pernambuco', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Volgograd', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Doha', 134);
 INSERT INTO estados (estado, id_pais) VALUES ('St. Andrew', 63);
 INSERT INTO estados (estado, id_pais) VALUES ('San Salvador', 36);
 INSERT INTO estados (estado, id_pais) VALUES ('Northern', 156);
 INSERT INTO estados (estado, id_pais) VALUES ('Tennessee', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Castilla and León', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Kowloon and New Kowl', 207);
 INSERT INTO estados (estado, id_pais) VALUES ('Aragonia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Lampung', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Santiago del Estero', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Tripura', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Tiaret', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Granma', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Bursa', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('North Gaza', 232);
 INSERT INTO estados (estado, id_pais) VALUES ('Yucatán', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Heilongjiang', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Akershus', 122);
 INSERT INTO estados (estado, id_pais) VALUES ('Khorazm', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Panamá', 127);
 INSERT INTO estados (estado, id_pais) VALUES ('Guangxi', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Asturia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('St Thomas', 231);
 INSERT INTO estados (estado, id_pais) VALUES ('Plymouth', 216);
 INSERT INTO estados (estado, id_pais) VALUES ('Sagaing', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('District of Columbia', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Hunan', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Dnipropetrovsk', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Abidjan', 123);
 INSERT INTO estados (estado, id_pais) VALUES ('Québec', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Lagos', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Huila', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Inhambane', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Västernorrlands län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Mures', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Toscana', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Pyongyang-si', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Plovdiv', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Surkhondaryo', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Suceava', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Lodzkie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Vojvodina', 67);
 INSERT INTO estados (estado, id_pais) VALUES ('Zhejiang', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Nebraska', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Valencia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Oran', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Maryland', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Tete', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Acre', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Sharqiya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Sharqiya', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Rostov-na-Donu', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Zinder', 120);
 INSERT INTO estados (estado, id_pais) VALUES ('iauliai', 96);
 INSERT INTO estados (estado, id_pais) VALUES ('Satu Mare', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Oruro', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('Selangor', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Gharb-Chrarda-Béni H', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Loreto', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Trujillo', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Aden', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('East Kazakstan', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Alberta', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Jönköpings län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Mississippi', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Assam', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaluga', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Anambra & Enugu & Eb', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Northern Mindanao', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Kayseri', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Castries', 140);
 INSERT INTO estados (estado, id_pais) VALUES ('Santiago', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Rafah', 232);
 INSERT INTO estados (estado, id_pais) VALUES ('Ho Chi Minh City', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Boyacá', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Montserrado', 93);
 INSERT INTO estados (estado, id_pais) VALUES ('Amapá', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Kütahya', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Chaharmahal va Bakht', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Sahalin', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Tatarstan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Njazidja', 79);
 INSERT INTO estados (estado, id_pais) VALUES ('Kabardi-Balkaria', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Buenos Aires', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Shaanxi', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Mordva', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Afyon', 174);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 112);
 INSERT INTO estados (estado, id_pais) VALUES ('Nevada', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Curaçao', 193);
 INSERT INTO estados (estado, id_pais) VALUES ('Sofala', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Thessalia', 84);
 INSERT INTO estados (estado, id_pais) VALUES ('Risaralda', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Osrednjeslovenska', 154);
 INSERT INTO estados (estado, id_pais) VALUES ('Istanbul', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Eastern', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Sétif', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Kalmykia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Sergipe', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Kentucky', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Ciego de Ávila', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Chiang Mai', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Kabol', 1);
 INSERT INTO estados (estado, id_pais) VALUES ('Tanger-Tétouan', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Lviv', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Aguascalientes', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Quintana Roo', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Mamoutzou', 215);
 INSERT INTO estados (estado, id_pais) VALUES ('Tartumaa', 189);
 INSERT INTO estados (estado, id_pais) VALUES ('Grand Turk', 228);
 INSERT INTO estados (estado, id_pais) VALUES ('Mostaganem', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Karakalpakistan', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Baja California Sur', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Seoul', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Ica', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Pihkova', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Hlavní mesto Praha', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Tochigi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Mazowieckie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Yamagata', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Oita', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Tahiti', 223);
 INSERT INTO estados (estado, id_pais) VALUES ('Aquitaine', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Majuro', 106);
 INSERT INTO estados (estado, id_pais) VALUES ('Shanghai', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Assuan', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Jilin', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Bangkok', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('San Juan', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Barisal', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Sisilia', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Kalimantan Tengah', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Santa Cruz', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('Dashhowuz', 175);
 INSERT INTO estados (estado, id_pais) VALUES ('Lorraine', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Okayama', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Chari-Baguirmi', 171);
 INSERT INTO estados (estado, id_pais) VALUES ('Kinshasa', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Andhra Pradesh', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Daloa', 123);
 INSERT INTO estados (estado, id_pais) VALUES ('Yanggang', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Tula', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Sawhaj', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('San Pedro de Macorís', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Flevoland', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Coquimbo', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Nusa Tenggara Barat', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('New Hampshire', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Quang Binh', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Karat ai-T erkessia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Tripoli', 94);
 INSERT INTO estados (estado, id_pais) VALUES ('Basra', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Chhatisgarh', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('West Australia', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Udmurtia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Cizah', 182);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 218);
 INSERT INTO estados (estado, id_pais) VALUES ('T ernigiv', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Meghalaya', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Songkhla', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Esfahan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Hodeida', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('Adzaria [At ara]', 45);
 INSERT INTO estados (estado, id_pais) VALUES ('Plateau & Nassarawa', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Lilongwe', 100);
 INSERT INTO estados (estado, id_pais) VALUES ('Bandundu', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Tucumán', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Espírito Santo', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Oromia', 40);
 INSERT INTO estados (estado, id_pais) VALUES ('Lori', 10);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Buhayra', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Córdoba', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Fukushima', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Ancash', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Querétaro de Arteaga', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Bioko', 133);
 INSERT INTO estados (estado, id_pais) VALUES ('Teheran', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Varna', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Saha (Jakutia)', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Santander', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('El-Aaiún', 212);
 INSERT INTO estados (estado, id_pais) VALUES ('Tarija', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('La Rioja', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Diyarbakir', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Apure', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Århus', 166);
 INSERT INTO estados (estado, id_pais) VALUES ('Morogoro', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Khujand', 163);
 INSERT INTO estados (estado, id_pais) VALUES ('Ardebil', 57);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('T ita', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Bíobío', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Coímbra', 131);
 INSERT INTO estados (estado, id_pais) VALUES ('Sichuan', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Latakia', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Bratislava', 153);
 INSERT INTO estados (estado, id_pais) VALUES ('Baghdad', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Bryssel', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Illinois', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Cienfuegos', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Malopolskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Geneve', 161);
 INSERT INTO estados (estado, id_pais) VALUES ('Indiana', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Bukarest', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Puno', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('New Mexico', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Saint Helena', 225);
 INSERT INTO estados (estado, id_pais) VALUES ('Ajman', 8);
 INSERT INTO estados (estado, id_pais) VALUES ('Qaraghandy', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Virginia', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Moscow (City)', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Hordaland', 122);
 INSERT INTO estados (estado, id_pais) VALUES ('Qyzylorda', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Qina', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Villa Clara', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Horad Minsk', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Montenegro', 67);
 INSERT INTO estados (estado, id_pais) VALUES ('Inner Mongolia', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Lisboa', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Osijek-Baranja', 85);
 INSERT INTO estados (estado, id_pais) VALUES ('Golestan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Salta', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Yamalin Nenetsia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Piura', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Severní Cechy', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Los Lagos', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('West Greece', 84);
 INSERT INTO estados (estado, id_pais) VALUES ('Upolu', 145);
 INSERT INTO estados (estado, id_pais) VALUES ('Hongkong', 207);
 INSERT INTO estados (estado, id_pais) VALUES ('Arizona', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Querétaro', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Khorasan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Missouri', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Cagayan Valley', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Eastern Visayas', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Andijon', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Brandenburg', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Loja', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Chihuahua', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Cundinamarca', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Rjazan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Cross River', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Haskovo', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Damaskos', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Sindh', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('Kang-won', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('St George', 141);
 INSERT INTO estados (estado, id_pais) VALUES ('Sylhet', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Midlands', 191);
 INSERT INTO estados (estado, id_pais) VALUES ('Paraná', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Lusaka', 144);
 INSERT INTO estados (estado, id_pais) VALUES ('Chiapas', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('North Kazakstan', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Ishikawa', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 177);
 INSERT INTO estados (estado, id_pais) VALUES ('Qinghai', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Champagne-Ardenne', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Liepaja', 90);
 INSERT INTO estados (estado, id_pais) VALUES ('Kemerovo', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Carolina', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Fakaofo', 227);
 INSERT INTO estados (estado, id_pais) VALUES ('Mbeya', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Diyala', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Ordu', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Antioquia', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Corrientes', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('San Luis', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Chisinau', 111);
 INSERT INTO estados (estado, id_pais) VALUES ('Ivanovo', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Kelantan', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Gomel', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Astana', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Atacama', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Nusa Tenggara Timur', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Lugansk', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Jizní Morava', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Oaxaca', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('OŽHiggins', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Karotegin', 163);
 INSERT INTO estados (estado, id_pais) VALUES ('København', 166);
 INSERT INTO estados (estado, id_pais) VALUES ('Ziguinchor', 149);
 INSERT INTO estados (estado, id_pais) VALUES ('Michigan', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Pays de la Loire', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Santiago de Cuba', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Shizuoka', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Bern', 161);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Mindanao', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Sind', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('Nampo-si', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Nampula', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Alsace', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Serbia', 67);
 INSERT INTO estados (estado, id_pais) VALUES ('Ilam', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Dnjestria', 111);
 INSERT INTO estados (estado, id_pais) VALUES ('Yaracuy', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Gävleborgs län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Chagang', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Imereti', 45);
 INSERT INTO estados (estado, id_pais) VALUES ('Manica', 114);
 INSERT INTO estados (estado, id_pais) VALUES ('Hormozgan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Durango', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('T erkasy', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Tokat', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Mardin', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Krim', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 156);
 INSERT INTO estados (estado, id_pais) VALUES ('Bas-Zaïre', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Caguas', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Santa Ana', 36);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Jazira', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Kanagawa', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Sulawesi Tengah', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Azuay', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Hama', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Baskimaa', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('West Götanmaan län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Nayarit', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Savannakhet', 89);
 INSERT INTO estados (estado, id_pais) VALUES ('Slaskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Ba Ria-Vung Tau', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Khanh Hoa', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Boulkiemdé', 27);
 INSERT INTO estados (estado, id_pais) VALUES ('Jubbada Hoose', 155);
 INSERT INTO estados (estado, id_pais) VALUES ('Hwanghae P', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Hakassia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Dâmbovita', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Kastilia-La Mancha', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Shanxi', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('CAR', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Aydin', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Jizní Cechy', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Wielkopolskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Wilayah Persekutuan', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Bissau', 50);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Gharbiya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Skikda', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Hebei', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Dolnoslaskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Kangwon', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('irak', 10);
 INSERT INTO estados (estado, id_pais) VALUES ('Benue', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Chimborazo', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Balears', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Sanliurfa', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Ehime', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Pietari', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Viangchan', 89);
 INSERT INTO estados (estado, id_pais) VALUES ('Pusan', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Tel Aviv', 60);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Faiyum', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Shaba', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Nyanza', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Maramures', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Inner Harbour', 104);
 INSERT INTO estados (estado, id_pais) VALUES ('Malatya', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Bengasi', 94);
 INSERT INTO estados (estado, id_pais) VALUES ('Kyongsangbuk', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Herson', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Rift Valley', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Ulaanbaatar', 113);
 INSERT INTO estados (estado, id_pais) VALUES ('Tolima', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Hessen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Nouakchott', 107);
 INSERT INTO estados (estado, id_pais) VALUES ('Newmaa', 158);
 INSERT INTO estados (estado, id_pais) VALUES ('Madhya Pradesh', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Tunis', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('Darfur al-Shamaliya', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('St John', 7);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 117);
 INSERT INTO estados (estado, id_pais) VALUES ('Klaipeda', 96);
 INSERT INTO estados (estado, id_pais) VALUES ('Punjab', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('North Kivu', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Varsinais-Suomi', 158);
 INSERT INTO estados (estado, id_pais) VALUES ('Peking', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Pegu [Bago]', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Newfoundland', 70);
 INSERT INTO estados (estado, id_pais) VALUES ('Mekka', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Edo & Delta', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Donetsk', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Arkansas', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Kilis', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Constantine', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Chinandega', 119);
 INSERT INTO estados (estado, id_pais) VALUES ('Washington', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Masqat', 124);
 INSERT INTO estados (estado, id_pais) VALUES ('Sidi Bel Abbès', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Batna', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Novgorod', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Caras-Severin', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Altai', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Osmaniye', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Battambang', 68);
 INSERT INTO estados (estado, id_pais) VALUES ('National Capital Reg', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Atacora', 19);
 INSERT INTO estados (estado, id_pais) VALUES ('Alto Paraná', 129);
 INSERT INTO estados (estado, id_pais) VALUES ('Kouilou', 80);
 INSERT INTO estados (estado, id_pais) VALUES ('Pará', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Ghardaïa', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Amazonas', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('South Tarawa', 77);
 INSERT INTO estados (estado, id_pais) VALUES ('Antofagasta', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Gelderland', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Ubon Ratchathani', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Mérida', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Friuli-Venezia Giuli', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Drenthe', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Atyrau', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Chiba', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Rarotonga', 200);
 INSERT INTO estados (estado, id_pais) VALUES ('Çorum', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Aragua', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Päijät-Häme', 158);
 INSERT INTO estados (estado, id_pais) VALUES ('Nord-Pas-de-Calais', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Bulawayo', 191);
 INSERT INTO estados (estado, id_pais) VALUES ('Sivas', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Ankara', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Ponce', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Wasit', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Içel', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Steiermark', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('Lam Dong', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Sulawesi Utara', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Gauteng', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Izmir', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Brjansk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Masaya', 119);
 INSERT INTO estados (estado, id_pais) VALUES ('Skopje', 99);
 INSERT INTO estados (estado, id_pais) VALUES ('Guizhou', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Meknès-Tafilalet', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Sancti-Spíritus', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Port Said', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Extremadura', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Kilimanjaro', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Kairouan', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('Tamaulipas', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Dire Dawa', 40);
 INSERT INTO estados (estado, id_pais) VALUES ('Islamabad', 125);
 INSERT INTO estados (estado, id_pais) VALUES ('Manipur', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Murmansk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Auvergne', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('North West', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Galati', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Kochi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Grad Sofija', 26);
 INSERT INTO estados (estado, id_pais) VALUES ('Paramaribo', 159);
 INSERT INTO estados (estado, id_pais) VALUES ('Kano & Jigawa', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamilton', 197);
 INSERT INTO estados (estado, id_pais) VALUES ('Kien Giang', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Länsimaa', 208);
 INSERT INTO estados (estado, id_pais) VALUES ('Central Macedonia', 84);
 INSERT INTO estados (estado, id_pais) VALUES ('South Australia', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Littoral', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Hokkaido', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Minya', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Dili', 209);
 INSERT INTO estados (estado, id_pais) VALUES ('Santa Catarina', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Vladimir', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Karnataka', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Khulna', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Chollanam', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Qadisiya', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Orjol', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Akita', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Fars', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Belize City', 18);
 INSERT INTO estados (estado, id_pais) VALUES ('Fianarantsoa', 98);
 INSERT INTO estados (estado, id_pais) VALUES ('Béjaïa', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Bihor', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Budapest', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Mon', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Bujumbura', 28);
 INSERT INTO estados (estado, id_pais) VALUES ('Hainaut', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Guayas', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Eastern', 118);
 INSERT INTO estados (estado, id_pais) VALUES ('Zanjan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Oyo & Osun', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Lebap', 175);
 INSERT INTO estados (estado, id_pais) VALUES ('Timis', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaduna', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Taizz', 65);
 INSERT INTO estados (estado, id_pais) VALUES ('Kagawa', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Orissa', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Marche', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Francistown', 23);
 INSERT INTO estados (estado, id_pais) VALUES ('Maekel', 37);
 INSERT INTO estados (estado, id_pais) VALUES ('Luanda', 6);
 INSERT INTO estados (estado, id_pais) VALUES ('Dakhlet Nouâdhibou', 107);
 INSERT INTO estados (estado, id_pais) VALUES ('Liaoning', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Munster', 58);
 INSERT INTO estados (estado, id_pais) VALUES ('Wales', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('T eljabinsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Sucre', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Binh Thuan', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Buhoro', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Guatemala', 48);
 INSERT INTO estados (estado, id_pais) VALUES ('Grand Cayman', 199);
 INSERT INTO estados (estado, id_pais) VALUES ('Imbabura', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Grodno', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Punjab', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Maale', 101);
 INSERT INTO estados (estado, id_pais) VALUES ('Johor', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Bengkulu', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Miranda', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 73);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Federal', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Pyongan N', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Tbilisi', 45);
 INSERT INTO estados (estado, id_pais) VALUES ('Odesa', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Capital Region', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('San Juan', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Ohio', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Haute-Normandie', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Alagoas', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Phnom Penh', 68);
 INSERT INTO estados (estado, id_pais) VALUES ('Tambov', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Maharashtra', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Saint-Denis', 224);
 INSERT INTO estados (estado, id_pais) VALUES ('Sucre', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Lipetsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Khomas', 116);
 INSERT INTO estados (estado, id_pais) VALUES ('Alaska', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Jiangxi', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Caraga', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('East Azerbaidzan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 118);
 INSERT INTO estados (estado, id_pais) VALUES ('Inchon', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Pichincha', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Beirut', 92);
 INSERT INTO estados (estado, id_pais) VALUES ('West Flanderi', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Utah', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Dar es Salaam', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Tabuk', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Jakarta Raya', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Zulia', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Ilocos', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('West Bengali', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Semnan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Magadan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Voronez', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Edirne', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Noord-Holland', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Niedersachsen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Bolívar', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Irkutsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Bihar', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Pinar del Río', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('T uvassia', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Annaba', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Höfuðborgarsvæði', 59);
 INSERT INTO estados (estado, id_pais) VALUES ('West Kazakstan', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Hims', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Tulcea', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Smolensk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Woqooyi Galbeed', 155);
 INSERT INTO estados (estado, id_pais) VALUES ('Manabí', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Nam Ha', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Zawiya', 94);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Federal', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Zaporizzja', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('West Kasai', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Roraima', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Ternopil', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Split-Dalmatia', 85);
 INSERT INTO estados (estado, id_pais) VALUES ('Kedah', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Centre', 69);
 INSERT INTO estados (estado, id_pais) VALUES ('Ivano-Frankivsk', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Tamim', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Oregon', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Aichi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Delhi', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Florida', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Taka-Karpatia', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Latium', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Ucayali', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Yamaguchi', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Taegu', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Shamal Sina', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Bamako', 103);
 INSERT INTO estados (estado, id_pais) VALUES ('Basse-Terre', 205);
 INSERT INTO estados (estado, id_pais) VALUES ('Qostanay', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Tokyo-to', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Abu Dhabi', 8);
 INSERT INTO estados (estado, id_pais) VALUES ('Ningxia', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Miyazaki', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Minsk', 183);
 INSERT INTO estados (estado, id_pais) VALUES ('Västerbottens län', 138);
 INSERT INTO estados (estado, id_pais) VALUES ('Mahé', 150);
 INSERT INTO estados (estado, id_pais) VALUES ('Arecibo', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaunas', 96);
 INSERT INTO estados (estado, id_pais) VALUES ('Uljanovsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Kigali', 137);
 INSERT INTO estados (estado, id_pais) VALUES ('Chlef', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamgyong N', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Falcón', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Pohnpei', 110);
 INSERT INTO estados (estado, id_pais) VALUES ('South Carolina', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Utrecht', 2);
 INSERT INTO estados (estado, id_pais) VALUES ('Tver', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Tungurahua', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Vrancea', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('New South Wales', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Baranya', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Erzincan', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Ninawa', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Holguín', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Amman', 66);
 INSERT INTO estados (estado, id_pais) VALUES ('Kafr al-Shaykh', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Harjumaa', 189);
 INSERT INTO estados (estado, id_pais) VALUES ('Las Tunas', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Haute-Zaïre', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Balkh', 1);
 INSERT INTO estados (estado, id_pais) VALUES ('North Carolina', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Colima', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('ARMM', 42);
 INSERT INTO estados (estado, id_pais) VALUES ('Dodoma', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('England', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('Pavlodar', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Sfax', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('National Capital Dis', 128);
 INSERT INTO estados (estado, id_pais) VALUES ('San Miguel', 36);
 INSERT INTO estados (estado, id_pais) VALUES ('Namur', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Chaco', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Morelos', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Magdalena', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Tutuila', 194);
 INSERT INTO estados (estado, id_pais) VALUES ('Schaan', 95);
 INSERT INTO estados (estado, id_pais) VALUES ('Western', 151);
 INSERT INTO estados (estado, id_pais) VALUES ('Constanta', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Taraz', 72);
 INSERT INTO estados (estado, id_pais) VALUES ('Chungchongnam', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Kärnten', 62);
 INSERT INTO estados (estado, id_pais) VALUES ('East Falkland', 201);
 INSERT INTO estados (estado, id_pais) VALUES ('Caquetá', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Hainan', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Wisconsin', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Barinas', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Kahramanmaras', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Orenburg', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Brasov', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Bender (Tîghina)', 111);
 INSERT INTO estados (estado, id_pais) VALUES ('Hyogo', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Veracruz-Llave', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Shimane', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Chungchongbuk', 83);
 INSERT INTO estados (estado, id_pais) VALUES ('Ilan', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Arusha', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Rabat-Salé-Zammour-Z', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Baden-Württemberg', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Chittagong', 15);
 INSERT INTO estados (estado, id_pais) VALUES ('Nordjylland', 166);
 INSERT INTO estados (estado, id_pais) VALUES ('Fès-Boulemane', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Kostroma', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Santiago', 29);
 INSERT INTO estados (estado, id_pais) VALUES ('Fejér', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Kombo St Mary', 44);
 INSERT INTO estados (estado, id_pais) VALUES ('Kordestan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('La Romana', 33);
 INSERT INTO estados (estado, id_pais) VALUES ('Saitama', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Kassala', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Georgia', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Midi-Pyrénées', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Porto', 131);
 INSERT INTO estados (estado, id_pais) VALUES ('Qashqadaryo', 182);
 INSERT INTO estados (estado, id_pais) VALUES ('Mary', 175);
 INSERT INTO estados (estado, id_pais) VALUES ('Kars', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Louisiana', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Kyoto', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Ondo & Ekiti', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Bauchi & Gombe', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Valle', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Korhogo', 123);
 INSERT INTO estados (estado, id_pais) VALUES ('Victoria', 11);
 INSERT INTO estados (estado, id_pais) VALUES ('Nordrhein-Westfalen', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('St George', 47);
 INSERT INTO estados (estado, id_pais) VALUES ('Szabolcs-Szatmár-Ber', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Monagas', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Changhwa', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Distrito Federal', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('East Flanderi', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Bani Suwayf', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Bouaké', 123);
 INSERT INTO estados (estado, id_pais) VALUES ('Schleswig-Holstein', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Oslo', 122);
 INSERT INTO estados (estado, id_pais) VALUES ('Tigray', 40);
 INSERT INTO estados (estado, id_pais) VALUES ('Georgetown', 51);
 INSERT INTO estados (estado, id_pais) VALUES ('Riika', 90);
 INSERT INTO estados (estado, id_pais) VALUES ('Mie', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Nagano', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('California', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('São Paulo', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Györ-Moson-Sopron', 179);
 INSERT INTO estados (estado, id_pais) VALUES ('Jharkhand', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Madrid', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Piemonte', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Imo & Abia', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Cesar', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('St Michael', 16);
 INSERT INTO estados (estado, id_pais) VALUES ('Pulau Pinang', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamadan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('Jersey', 24);
 INSERT INTO estados (estado, id_pais) VALUES ('Mykolajiv', 178);
 INSERT INTO estados (estado, id_pais) VALUES ('Equateur', 81);
 INSERT INTO estados (estado, id_pais) VALUES ('Katalonia', 38);
 INSERT INTO estados (estado, id_pais) VALUES ('Irbil', 56);
 INSERT INTO estados (estado, id_pais) VALUES ('Streymoyar', 202);
 INSERT INTO estados (estado, id_pais) VALUES ('Arkangeli', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Hidalgo', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Zufar', 124);
 INSERT INTO estados (estado, id_pais) VALUES ('Ogun', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Santafé de Bogotá', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Borgou', 19);
 INSERT INTO estados (estado, id_pais) VALUES ('Dunedin', 181);
 INSERT INTO estados (estado, id_pais) VALUES ('Maseru', 91);
 INSERT INTO estados (estado, id_pais) VALUES ('El Oro', 34);
 INSERT INTO estados (estado, id_pais) VALUES ('Kujawsko-Pomorskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Basse-Normandie', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Northern Cape', 39);
 INSERT INTO estados (estado, id_pais) VALUES ('Carabobo', 186);
 INSERT INTO estados (estado, id_pais) VALUES ('Michoacán de Ocampo', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Toamasina', 98);
 INSERT INTO estados (estado, id_pais) VALUES ('Blida', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamilton', 181);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 196);
 INSERT INTO estados (estado, id_pais) VALUES ('Primorje-Gorski Kota', 85);
 INSERT INTO estados (estado, id_pais) VALUES ('Niger', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Casablanca', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Koror', 126);
 INSERT INTO estados (estado, id_pais) VALUES ('Tacna', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Batina', 124);
 INSERT INTO estados (estado, id_pais) VALUES ('Sinaloa', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Saga', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Dagestan', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Karaman', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Tanga', 165);
 INSERT INTO estados (estado, id_pais) VALUES ('Bourgogne', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Vaud', 161);
 INSERT INTO estados (estado, id_pais) VALUES ('Manicaland', 191);
 INSERT INTO estados (estado, id_pais) VALUES ('Krasnojarsk', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Mato Grosso', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Baja California', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('México', 109);
 INSERT INTO estados (estado, id_pais) VALUES ('Aleppo', 162);
 INSERT INTO estados (estado, id_pais) VALUES ('Sør-Trøndelag', 122);
 INSERT INTO estados (estado, id_pais) VALUES ('Entre Rios', 9);
 INSERT INTO estados (estado, id_pais) VALUES ('Matanzas', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Hiroshima', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Veneto', 61);
 INSERT INTO estados (estado, id_pais) VALUES ('Callao', 130);
 INSERT INTO estados (estado, id_pais) VALUES ('Kalimantan Selatan', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Vâlcea', 136);
 INSERT INTO estados (estado, id_pais) VALUES ('Henan', 75);
 INSERT INTO estados (estado, id_pais) VALUES ('Chuquisaca', 21);
 INSERT INTO estados (estado, id_pais) VALUES ('Guaynabo', 221);
 INSERT INTO estados (estado, id_pais) VALUES ('Warminsko-Mazurskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Rangoon [Yangon]', 115);
 INSERT INTO estados (estado, id_pais) VALUES ('Hamgyong P', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Liège', 17);
 INSERT INTO estados (estado, id_pais) VALUES ('Tébessa', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Pondicherry', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Île-de-France', 135);
 INSERT INTO estados (estado, id_pais) VALUES ('Alger', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Irbid', 66);
 INSERT INTO estados (estado, id_pais) VALUES ('Bahr al-Jabal', 157);
 INSERT INTO estados (estado, id_pais) VALUES ('Central', 144);
 INSERT INTO estados (estado, id_pais) VALUES ('Sumatera Barat', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Cauca', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Oklahoma', 190);
 INSERT INTO estados (estado, id_pais) VALUES ('Oriental', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Iwate', 64);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 203);
 INSERT INTO estados (estado, id_pais) VALUES ('Mizoram', 55);
 INSERT INTO estados (estado, id_pais) VALUES ('Souss Massa-Draâ', 105);
 INSERT INTO estados (estado, id_pais) VALUES ('Aqua Grande', 147);
 INSERT INTO estados (estado, id_pais) VALUES ('Pingtung', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Baijeri', 142);
 INSERT INTO estados (estado, id_pais) VALUES ('Lubuskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Severní Morava', 172);
 INSERT INTO estados (estado, id_pais) VALUES ('Jambi', 54);
 INSERT INTO estados (estado, id_pais) VALUES ('Piauí', 192);
 INSERT INTO estados (estado, id_pais) VALUES ('Guantánamo', 86);
 INSERT INTO estados (estado, id_pais) VALUES ('Hmelnytskyi', 178);
 INSERT INTO estados (estado, id_pais) VALUES (' ', 219);
 INSERT INTO estados (estado, id_pais) VALUES ('San Miguelito', 127);
 INSERT INTO estados (estado, id_pais) VALUES ('Kamt atka', 187);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaohsiung', 164);
 INSERT INTO estados (estado, id_pais) VALUES ('Kaesong-si', 82);
 INSERT INTO estados (estado, id_pais) VALUES ('Nonthaburi', 167);
 INSERT INTO estados (estado, id_pais) VALUES ('Katsina', 121);
 INSERT INTO estados (estado, id_pais) VALUES ('Quang Ninh', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Yamoussoukro', 123);
 INSERT INTO estados (estado, id_pais) VALUES ('Biskra', 4);
 INSERT INTO estados (estado, id_pais) VALUES ('Kairo', 35);
 INSERT INTO estados (estado, id_pais) VALUES ('Sousse', 173);
 INSERT INTO estados (estado, id_pais) VALUES ('Sabah', 102);
 INSERT INTO estados (estado, id_pais) VALUES ('al-Khudud al-Samaliy', 148);
 INSERT INTO estados (estado, id_pais) VALUES ('Lorestan', 57);
 INSERT INTO estados (estado, id_pais) VALUES ('An Giang', 188);
 INSERT INTO estados (estado, id_pais) VALUES ('Siirt', 174);
 INSERT INTO estados (estado, id_pais) VALUES ('Estuaire', 43);
 INSERT INTO estados (estado, id_pais) VALUES ('Swietokrzyskie', 132);
 INSERT INTO estados (estado, id_pais) VALUES ('Bishkek shaary', 76);
 INSERT INTO estados (estado, id_pais) VALUES ('La Guajira', 78);
 INSERT INTO estados (estado, id_pais) VALUES ('Tokushima', 64);
 INSERT INTO estados (estado, id_pais) VALUES ('Cap-Vert', 149);
