 INSERT INTO formas_de_governo (forma_governo) VALUES ('Occupied by Marocco');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Nonmetropolitan Territory of France');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Co-administrated');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Territory of Australia');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Dependent Territory of Norway');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Parlementary Monarchy');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Territorial Collectivity of France');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Overseas Department of France');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Part of Denmark');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Federal Republic');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Monarchy (Sultanate)');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Monarchy');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Administrated by the UN');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Federation');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Socialistic Republic');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Nonmetropolitan Territory of The Netherlands');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Emirate Federation');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Republic');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('US Territory');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Commonwealth of the US');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Constitutional Monarchy (Emirate)');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Parliamentary Coprincipality');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Autonomous Area');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Islamic Republic');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Nonmetropolitan Territory of New Zealand');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('PeoplesRepublic');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Constitutional Monarchy');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Monarchy (Emirate)');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Socialistic State');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Special Administrative Region of China');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Islamic Emirate');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Constitutional Monarchy, Federation');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Dependent Territory of the UK');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Independent Church State');
 INSERT INTO formas_de_governo (forma_governo) VALUES ('Dependent Territory of the US');
