 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Netherlands Antilles', 'ANT', 217000, 800.00,  5, 16);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('American Samoa', 'ASM', 68000, 199.00,  3, 19);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Anguilla', 'AIA', 8000, 96.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Aruba', 'ABW', 103000, 193.00,  5, 16);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Bermuda', 'BMU', 65000, 53.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Virgin Islands, British', 'VGB', 21000, 151.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Cayman Islands', 'CYM', 38000, 264.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Cook Islands', 'COK', 20000, 236.00,  3, 25);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Falkland Islands', 'FLK', 2000, 12173.00,  6, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Faroe Islands', 'FRO', 43000, 1399.00,  2, 9);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Gibraltar', 'GIB', 25000, 6.00,  2, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Greenland', 'GRL', 56000, 2166090.00,  5, 9);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Guadeloupe', 'GLP', 456000, 1705.00,  5, 8);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Guam', 'GUM', 168000, 549.00,  3, 19);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Hong Kong', 'HKG', 6782000, 1075.00,  7, 30);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Svalbard and Jan Mayen', 'SJM', 3200, 62422.00,  2, 5);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('East Timor', 'TMP', 885000, 14874.00,  7, 13);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Christmas Island', 'CXR', 2500, 135.00,  3, 4);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Cocos (Keeling) Islands', 'CCK', 600, 14.00,  3, 4);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Western Sahara', 'ESH', 293000, 266000.00,  1, 1);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Macao', 'MAC', 473000, 18.00,  7, 30);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Martinique', 'MTQ', 395000, 1102.00,  5, 8);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Mayotte', 'MYT', 149000, 373.00,  1, 7);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Montserrat', 'MSR', 11000, 102.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Niue', 'NIU', 2000, 260.00,  3, 25);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Norfolk Island', 'NFK', 2000, 36.00,  3, 4);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Pitcairn', 'PCN', 50, 49.00,  3, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Northern Mariana Islands', 'MNP', 78000, 464.00,  3, 20);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Puerto Rico', 'PRI', 3869000, 8875.00,  5, 20);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('French Guiana', 'GUF', 181000, 90000.00,  6, 8);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('French Polynesia', 'PYF', 235000, 4000.00,  3, 2);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Réunion', 'REU', 699000, 2510.00,  1, 8);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Saint Helena', 'SHN', 6000, 314.00,  1, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Saint Pierre and Miquelon', 'SPM', 7000, 242.00,  5, 7);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Tokelau', 'TKL', 2000, 12.00,  3, 25);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Turks and Caicos Islands', 'TCA', 17000, 430.00,  5, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('New Caledonia', 'NCL', 214000, 18575.00,  3, 2);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Wallis and Futuna', 'WLF', 15000, 200.00,  3, 2);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Virgin Islands, U.S.', 'VIR', 93000, 347.00,  5, 19);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Palestine', 'PSE', 3101000, 6257.00,  7, 23);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Antarctica', 'ATA', 0, 13120000.00,  4, 3);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Bouvet Island', 'BVT', 0, 59.00,  4, 5);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('British Indian Ocean Territory', 'IOT', 0, 78.00,  1, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('South Georgia and the South Sandwich Islands', 'SGS', 0, 3903.00,  4, 33);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('Heard Island and McDonald Islands', 'HMD', 0, 359.00,  4, 4);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('French Southern territories', 'ATF', 0, 7780.00,  4, 2);
 INSERT INTO paises (pais, codigo, populacao, area, id_continente, id_forma_governo) VALUES ('United States Minor Outlying Islands', 'UMI', 0, 16.00,  3, 35);
